#!/bin/csh -f
if ($#argv == 0) then
    echo getMotifs seqfile [-s cutoff]
else if ($#argv == 1) then

/home/a-m/jssong/UCSF_home/jssong/bin/Markov0-9/MarkovScan -c 5 -d /home/a-m/jssong/UCSF_home/jssong/Research/PSSM_Matrices/DFCI_Matrices/ -m 2   $1

/home/a-m/jssong/UCSF_home/jssong/bin/Markov0-9/MarkovScan -c 5 -d /home/a-m/jssong/UCSF_home/jssong/Research/PSSM_Matrices/JASPAR_Matrices/ -m 2   $1

/home/a-m/jssong/UCSF_home/jssong/bin/Markov0-9/MarkovScan -c 5 -d /home/a-m/jssong/UCSF_home/jssong/Research/PSSM_Matrices/TRANSFAC_Matrices_Human/ -m 2  $1

else if  ($#argv == 2) then

/home/a-m/jssong/UCSF_home/jssong/bin/Markov0-9/MarkovScan -s $2 -d /home/a-m/jssong/UCSF_home/jssong/Research/PSSM_Matrices/DFCI_Matrices/ -m 2  $1

/home/a-m/jssong/UCSF_home/jssong/bin/Markov0-9/MarkovScan -s $2 -d /home/a-m/jssong/UCSF_home/jssong/Research/PSSM_Matrices/JASPAR_Matrices/ -m 2   $1

/home/a-m/jssong/UCSF_home/jssong/bin/Markov0-9/MarkovScan -s $2 -d /home/a-m/jssong/UCSF_home/jssong/Research/PSSM_Matrices/TRANSFAC_Matrices_Human/ -m 2  $1

endif
